# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Build site and deploy

jobs:
  renderbook:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Install udunits
        run: |
          brew install udunits
          
      # renv details from https://github.com/actions/cache/blob/master/examples.md#r---renv
      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Build site
        shell: Rscript {0}
        run: |
          renv::install("bslib")
          renv::install("downlit")
          bookdown::render_book("index.Rmd", quiet = TRUE)

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: _book
          path: docs/


  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: renderbook
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          # Artifact name
          name: _book
          # Destination path
          path: docs
      # deploy to Github pages from https://github.com/Cecilapp/GitHub-Pages-deploy
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: wfmackey@gmail.com
          build_dir: docs